stages:
  - deploy

deploy-railway:
  stage: deploy
  image: ubuntu
  only:
    - main
  script:
    - apt-get update && apt-get install -y curl
    - bash <(curl -fsSL cli.new)
    - railway up --service=$RAILWAY_SERVICE_NAME -d